import os
import pandas as pd
from pymongo import MongoClient

# Configuration
# This points to the file generated by balanced_sentiment.py in the root directory
CSV_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "balanced_sentiment_dataset.csv",
)

MONGO_URI = "mongodb://localhost:27017/"
DB_NAME = "sentimentDB"
COLLECTION_NAME = "balanced_text_data"
CHUNK_SIZE = 100_000  # Insert 100k records at a time to manage memory

def main():
    print(f"[*] Loading augmented dataset from {CSV_PATH}...")
    if not os.path.exists(CSV_PATH):
        print(f"[!] Error: {CSV_PATH} not found.")
        print("Please run 'python balanced_sentiment.py' first and wait for it to finish.")
        return

    # 1. Load the data
    print("[*] Reading CSV file (this might take a moment for 3 million rows)...")
    df = pd.read_csv(CSV_PATH)
    
    # Drop rows with missing values just in case
    df = df.dropna(subset=["clean_text", "sentiment"])
    df["clean_text"] = df["clean_text"].astype(str)
    
    total_rows = len(df)
    print(f"[*] Dataset successfully loaded with {total_rows:,} valid rows.")
    
    # 2. Connect to MongoDB
    print(f"[*] Connecting to MongoDB at {MONGO_URI}...")
    try:
        client = MongoClient(MONGO_URI, serverSelectionTimeoutMS=5000)
        # Test connection
        client.admin.command('ping')
    except Exception as e:
        print(f"[!] Could not connect to MongoDB: {e}")
        print("Please make sure your local MongoDB server is running.")
        return

    db = client[DB_NAME]
    collection = db[COLLECTION_NAME]
    
    # 3. Clear existing collection
    print(f"[*] Dropping existing collection '{COLLECTION_NAME}' (if any)...")
    collection.drop()

    # 4. Insert data in chunks
    print(f"[*] Inserting {total_rows:,} records into MongoDB...")
    
    # Convert DataFrame to list of dicts (for MongoDB)
    records = df.to_dict(orient="records")
    
    total_inserted = 0
    for i in range(0, len(records), CHUNK_SIZE):
        chunk = records[i : i + CHUNK_SIZE]
        collection.insert_many(chunk)
        total_inserted += len(chunk)
        print(f"    -> Inserted {total_inserted:,} / {total_rows:,} records")
        
    print("\n[✔] Success! All records inserted successfully.")
    
    # Verify count in MongoDB
    actual_count = collection.count_documents({})
    print(f"[✔] MongoDB collection '{COLLECTION_NAME}' now contains {actual_count:,} documents.")

if __name__ == "__main__":
    main()
